# Generated by Django 5.0.6 on 2024-06-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cme',
            name='credits',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
